---
title: "EPID 600 Project Template"
author: "Your Name"
output: html_document
---

Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Due dates:

- Topic choice: 9/18/15
- List of faculty/staff to be contacted: 10/2/15
- Complete overview with data source to address a specific problem identified: 10/16/15
- Introduction: 11/9/15
- Methods and Results draft: 11/23/15
- Final Document: 12/11/15

### Overview
In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.


### Introduction 
In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.

In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

Epilepsy is a neurological disorder that affects more than 60 million people worldwide, or approximately 1% of the population.  In 37% of epilepsy patients, seizure generation is resistant to medication [French 2007]. For some drug-resistant patients, resective surgery to remove seizure-generating regions is an option. However, post-resection outcome is modest, ~40% seizure-free in patients without focal lesions and 65% in well localized patients.  The need for novel, more effective therapies is clear. A recent innovation in the treatment of drug-resistant epilepsy is chronic, implantable devices that stimulate brain networks in response to epileptic events. These devices abort seizure activity by detecting seizure-generation and delivering electrical stimulation to network targets, reducing monthly seizure rates by as much as 41.5% [Lega 2010][ DeGiorgio 2013]. The success of implantable devices hinges on algorithms that detect seizure-generation, such as the one I will be developing in this project.

This is an interdisciplinary problem that pulls from the fields of neuroscience, signal processing, computer science, and data science. Neuroscience provides us with the knowledge of what is physiologically happening during a seizure as well as what defines a seizure. We can then leverage methods developed from signal processing and computer science to extract and process information from the brain before implementing a machine learning algorithm to detect seizure generation. Machine learning techniques are especially important here, where specific algorithms are more suited to data with a class imbalance as seen in this problem when seizures are few and far between. Finally, EEG recordings produce massive amounts of data that needs to be handled efficiently. Data science gives us the tools to organize and analyze this data. 

### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

Four intracranial EEG data sets hosted on the ieeg.org portal were selected for use in my study. These data sets were recorded from dogs with naturally occurring epilepsy using an ambulatory monitoring system. EEG from the dogs was acquired from an implanted device with a sampling rate of 400Hz from 16 subdural electrodes arranged on two 4-contact strips implanted on each hemisphere in an antero-posterior position.  

To prepare the data for use in the study, data sets were split into a training set and a testing set. Testing and training data were organized into one-second clips where training data clips were labeled ‘ictal’ for the seizure data segments or ‘inter-ictal’ for non-seizure data segments and testing clips remained unlabeled.  Training data clips were arranged sequentially, while testing data clips were in random order.  Ictal segments cover the entire seizure and inter-ictal segments cover approximately the mean of seizure duration. Inter-ictal segments were chosen randomly under the provision that they were not within one hour before or after a seizure.

Features were extracted from each clip. These features include the log10 magnitude of the frequencies, correlation coefficients between channels, and their corresponding sorted eigenvalues in both the time and frequency domains. These features are ran through a random forest classifier so that each clip may be labeled ictal or interictal.

```{r eval=FALSE}
library(R.matlab)
library(stats)
library(gtools)
library(randomForest)
library(e1071)
######################################## FUNCTIONS #######################################

## Function to load .mat files into R
loadMat = function(fileName)
{
  # Load in mat file and read the fields into variables
  rawData = readMat(fileName)
  out = list(data=rawData['data'],freq = rawData['freq'],latency = rawData['latency'])
}

## function to extract features from EEG data
extractFeats = function(data)
{
  
  # normalize channels
  norm_data = data.frame((data-rowMeans(data))/apply(data,1,sd))
  
  # calculate time frequency correlation matrix
  corr_matrix = cor(norm_data)
  
  # sorted eigen values
  eigen_values = eigen(corr_matrix)$values
  
  # upper right triangular to eliminate redundant features
  uppr_right = corr_matrix[upper.tri(corr_matrix,diag = FALSE)]
  
  # Frequency Domain
  # fft magnitudes of 1-47Hz
  fdata = abs(fft(data))
  fdata = fdata + 2e-13
  fdata = log10(fdata[1:47,])
  logdata = as.vector(fdata)
  
  # normalize by frequency bin
  ddata = ((fdata-rowMeans(fdata))/apply(fdata,1,sd))
  
  # calculate time frequency correlation matrix
  fcorr_matrix = cor(fdata)
  
  # sorted eigen values
  feigen_values = eigen(fcorr_matrix)$values
  
  # upper right triangular to eliminate redundant features
  fuppr_right = fcorr_matrix[upper.tri(fcorr_matrix,diag = FALSE)]
  
  # concatenate features into a vector
  feature_vec = c(eigen_values,feigen_values,logdata,uppr_right,fuppr_right)
  
}

# clip dimensions
#size = as.data.frame(lapply(clip$data, dim))


#################################### PROCESS SUBJECTS ####################################

### Subjects in study
subjects = c('Dog_1','Dog_2','Dog_3','Dog_4')

## Process subjects
for (i in 1:length(subjects)){
  print(i)
  # ictal clip paths
  clips.ictal = list.files(paste('Documents/Volumes/Seagate/seizure_detection/competition_data/clips/',subjects[i],sep = ''), pattern="*ictal*", full.names=TRUE)
  clips.ictal = clips.ictal[mixedorder(clips.ictal)]
  
  # interictal clip paths
  clips.interictal = list.files(paste('Documents/Volumes/Seagate/seizure_detection/competition_data/clips/',subjects[i],sep = ''), pattern="*interictal*", full.names=TRUE)
  clips.interictal = clips.interictal[mixedorder(clips.interictal)]
  
  # test clip paths
  clips.test = list.files(paste('Documents/Volumes/Seagate/seizure_detection/competition_data/clips/',subjects[i],sep = ''), pattern="*test*", full.names=TRUE)
  clips.test = clips.test[mixedorder(clips.test)]
  
  ## process ictal clips
  for (ict in 1:length(clips.ictal)){
    
    # load clip
    clip = loadMat(clips.ictal[ict])
  
    # convert to matrix
    data = matrix(unlist(clip$data),round(as.numeric(clip$freq)), byrow = TRUE)
    
    # extract features and create feature matrix
    if (ict == 1){
      ictal_feats = extractFeats(data)
    } else {
    ictal_feats = rbind(ictal_feats,extractFeats(data))
    }
   
  }
  print('ictal clips done!')
  
  ## process interictal clips
  for (intict in 1:length(clips.interictal)){
    
    # load clip
    clip = loadMat(clips.interictal[intict])
    
    # convert to matrix
    data = matrix(unlist(clip$data),round(as.numeric(clip$freq)), byrow = TRUE)
    
    # extract features and create feature matrix
    if (intict == 1){
      interictal_feats = extractFeats(data)
    } else {
      interictal_feats = rbind(interictal_feats,extractFeats(data))
    }
    
  }
  
  print('interictal clips done!')
  ## process test clips
  for (tes in 1:length(clips.test)){
    # load clip
    clip = loadMat(clips.test[tes])
    
    # convert to matrix
    data = matrix(unlist(clip$data),round(as.numeric(clip$freq)), byrow = TRUE)
    
    # extract features and create feature matrix
    if (tes == 1){
      test_feats = extractFeats(data)
    } else {
      test_feats = rbind(test_feats,extractFeats(data))
    }
    
  }
  print('test clips done!')
  ## store feature matrices in list of subjects
  if (i == 1) {
    features.ictal = list(ictal_feats)
    features.interictal = list(interictal_feats)
    features.test = list(test_feats)
  } else {
    features.ictal[[i]] = ictal_feats
    features.interictal[[i]] = interictal_feats
    features.test[[i]] = test_feats
  }
  print('features stored!')
}



# import test labels


########################## SEIZURE DETECTION ALGORITHMS/SUBJECT ##########################
# random forest
pred.rf = list()
for (i in 1:length(subjects)){
  print('')
  
  # Make labels
  labels.ictal = rep(1,dim(features.ictal[[i]])[1])
  labels.interictal = rep(0,dim(features.interictal[[i]])[1])
  
  # random forest
  detector.rf = randomForest(rbind(features.ictal[[i]],features.interictal[[i]]),factor(c(labels.ictal,labels.interictal)),ntree=100,importance=TRUE) 
  
  # make predictions
  pred.rf[[i]] = predict(detector.rf,features.test[[i]], type="prob")
}

```



### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address.

I'm still working on results...
